version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: dm-copilot-postgres
    environment:
      POSTGRES_DB: dm_copilot
      POSTGRES_USER: dm_user
      POSTGRES_PASSWORD: dm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dm_user -d dm_copilot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
