[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-orchestrate-simple"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
